$countries = array(
  array('country_id' => '19','name' => 'Австралия','currency_code' => 'AUD','currency' => 'Австралийский доллар'),
  array('country_id' => '20','name' => 'Австрия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '5','name' => 'Азербайджан','currency_code' => 'AZN','currency' => 'Азербайджанский манат'),
  array('country_id' => '21','name' => 'Албания','currency_code' => 'ALB','currency' => 'Лек'),
  array('country_id' => '22','name' => 'Алжир','currency_code' => 'DZD','currency' => 'Алжирский динар'),
  array('country_id' => '23','name' => 'Американское Самоа','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '24','name' => 'Ангилья','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '25','name' => 'Ангола','currency_code' => 'AOA','currency' => 'Кванза'),
  array('country_id' => '26','name' => 'Андорра','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '27','name' => 'Антигуа и Барбуда','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '28','name' => 'Аргентина','currency_code' => 'ARS','currency' => 'Аргентинское песо'),
  array('country_id' => '6','name' => 'Армения','currency_code' => 'AMD','currency' => 'Армянский драм'),
  array('country_id' => '29','name' => 'Аруба','currency_code' => 'AWG','currency' => 'Арубанский флорин'),
  array('country_id' => '30','name' => 'Афганистан','currency_code' => 'AFN','currency' => 'Афгани'),
  array('country_id' => '31','name' => 'Багамы','currency_code' => 'BSD','currency' => 'Багамский доллар'),
  array('country_id' => '32','name' => 'Бангладеш','currency_code' => 'BTD','currency' => 'Така'),
  array('country_id' => '33','name' => 'Барбадос','currency_code' => 'BBD','currency' => 'Барбадосский доллар'),
  array('country_id' => '34','name' => 'Бахрейн','currency_code' => 'BHD','currency' => 'Бахрейнский динар'),
  array('country_id' => '3','name' => 'Беларусь','currency_code' => 'BYR','currency' => 'Белорусский рубль'),
  array('country_id' => '35','name' => 'Белиз','currency_code' => 'BZD','currency' => 'Белизский доллар '),
  array('country_id' => '36','name' => 'Бельгия','currency_code' => 'Евро','currency' => 'EUR'),
  array('country_id' => '37','name' => 'Бенин','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '38','name' => 'Бермуды','currency_code' => 'BMD','currency' => 'Бермудский доллар'),
  array('country_id' => '39','name' => 'Болгария','currency_code' => 'BGN','currency' => 'Болгарский лев'),
  array('country_id' => '40','name' => 'Боливия','currency_code' => 'BOB','currency' => 'Боливиано'),
  array('country_id' => '41','name' => 'Босния и Герцеговина','currency_code' => 'BAM','currency' => 'Конвертируемая марка'),
  array('country_id' => '42','name' => 'Ботсвана','currency_code' => 'BWP','currency' => 'Пула'),
  array('country_id' => '43','name' => 'Бразилия','currency_code' => 'BRL','currency' => 'Бразильский реал'),
  array('country_id' => '44','name' => 'Бруней-Даруссалам','currency_code' => 'BND','currency' => 'Брунейский доллар'),
  array('country_id' => '45','name' => 'Буркина-Фасо','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '46','name' => 'Бурунди','currency_code' => 'BIF','currency' => 'Бурундийский франк'),
  array('country_id' => '47','name' => 'Бутан','currency_code' => 'BTN','currency' => 'Нгултрум'),
  array('country_id' => '48','name' => 'Вануату','currency_code' => 'VUV','currency' => 'Вату'),
  array('country_id' => '49','name' => 'Великобритания','currency_code' => 'GBP','currency' => 'Фунт стерлингов'),
  array('country_id' => '50','name' => 'Венгрия','currency_code' => 'HUF','currency' => 'Форинт'),
  array('country_id' => '51','name' => 'Венесуэла','currency_code' => 'VEF','currency' => 'Боливар фуэрте'),
  array('country_id' => '52','name' => 'Виргинские острова, Британские','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '53','name' => 'Виргинские острова, США','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '54','name' => 'Восточный Тимор','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '55','name' => 'Вьетнам','currency_code' => 'VND','currency' => 'Донг'),
  array('country_id' => '56','name' => 'Габон','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '57','name' => 'Гаити','currency_code' => 'HTG','currency' => 'Гурд'),
  array('country_id' => '58','name' => 'Гайана','currency_code' => 'GYD','currency' => 'Гайанский доллар'),
  array('country_id' => '59','name' => 'Гамбия','currency_code' => 'GMD','currency' => 'Даласи'),
  array('country_id' => '60','name' => 'Гана','currency_code' => 'GHC','currency' => 'Седи'),
  array('country_id' => '61','name' => 'Гваделупа','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '62','name' => 'Гватемала','currency_code' => 'GTQ','currency' => 'Кетсаль'),
  array('country_id' => '63','name' => 'Гвинея','currency_code' => 'GNF','currency' => 'Гвинейский франк'),
  array('country_id' => '64','name' => 'Гвинея-Бисау','currency_code' => 'XFO','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '65','name' => 'Германия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '66','name' => 'Гибралтар','currency_code' => 'GIP','currency' => 'Гибралтарский фунт'),
  array('country_id' => '67','name' => 'Гондурас','currency_code' => 'HNL','currency' => 'Лемпира'),
  array('country_id' => '68','name' => 'Гонконг','currency_code' => 'HKD','currency' => 'Гонконгский доллар'),
  array('country_id' => '69','name' => 'Гренада','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '70','name' => 'Гренландия','currency_code' => 'DKK','currency' => 'Датская крона'),
  array('country_id' => '71','name' => 'Греция','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '7','name' => 'Грузия','currency_code' => 'GEL','currency' => 'Лари'),
  array('country_id' => '72','name' => 'Гуам','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '73','name' => 'Дания','currency_code' => 'DKK','currency' => 'Датская крона'),
  array('country_id' => '231','name' => 'Джибути','currency_code' => 'DJF','currency' => 'Франк Джибути'),
  array('country_id' => '74','name' => 'Доминика','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '75','name' => 'Доминиканская Республика','currency_code' => 'DOP','currency' => 'Доминиканское песо'),
  array('country_id' => '76','name' => 'Египет','currency_code' => 'EGP','currency' => 'Египетский фунт'),
  array('country_id' => '77','name' => 'Замбия','currency_code' => 'ZMK','currency' => 'Замбийская квача'),
  array('country_id' => '78','name' => 'Западная Сахара','currency_code' => 'MAD','currency' => 'Марокканский дирхам'),
  array('country_id' => '79','name' => 'Зимбабве','currency_code' => 'ZWL','currency' => 'Доллар Зимбабве'),
  array('country_id' => '8','name' => 'Израиль','currency_code' => 'ILS','currency' => 'Новый израильский шекель'),
  array('country_id' => '80','name' => 'Индия','currency_code' => 'INR','currency' => 'Индийская рупия'),
  array('country_id' => '81','name' => 'Индонезия','currency_code' => 'IDR','currency' => 'Рупия'),
  array('country_id' => '82','name' => 'Иордания','currency_code' => 'JOD','currency' => 'Иорданский динар'),
  array('country_id' => '83','name' => 'Ирак','currency_code' => 'IQD','currency' => 'Иракский динар'),
  array('country_id' => '84','name' => 'Иран','currency_code' => 'IRR','currency' => 'Иранский риал'),
  array('country_id' => '85','name' => 'Ирландия','currency_code' => 'IEP','currency' => 'Ирландский фунт'),
  array('country_id' => '86','name' => 'Исландия','currency_code' => 'ISK','currency' => 'Исландская крона'),
  array('country_id' => '87','name' => 'Испания','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '88','name' => 'Италия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '89','name' => 'Йемен','currency_code' => 'YER','currency' => 'Йеменский риал'),
  array('country_id' => '90','name' => 'Кабо-Верде','currency_code' => 'CVE','currency' => 'Эскудо Кабо-Верде'),
  array('country_id' => '4','name' => 'Казахстан','currency_code' => 'KZT','currency' => 'Тенге'),
  array('country_id' => '91','name' => 'Камбоджа','currency_code' => 'KHR','currency' => 'Риель'),
  array('country_id' => '92','name' => 'Камерун','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '10','name' => 'Канада','currency_code' => 'CAD','currency' => 'Канадский доллар'),
  array('country_id' => '93','name' => 'Катар','currency_code' => 'QAR','currency' => 'Катарский риал'),
  array('country_id' => '94','name' => 'Кения','currency_code' => 'KES','currency' => 'Кенийский шиллинг'),
  array('country_id' => '95','name' => 'Кипр','currency_code' => 'CYP','currency' => 'Кипрский фунт'),
  array('country_id' => '96','name' => 'Кирибати','currency_code' => 'AUD','currency' => 'Австралийский доллар'),
  array('country_id' => '97','name' => 'Китай','currency_code' => 'CNY','currency' => 'Юань'),
  array('country_id' => '98','name' => 'Колумбия','currency_code' => 'COP','currency' => 'Колумбийское песо'),
  array('country_id' => '99','name' => 'Коморы','currency_code' => 'KMF','currency' => 'Франк Комор'),
  array('country_id' => '100','name' => 'Конго','currency_code' => 'CDF','currency' => 'Конголезский франк'),
  array('country_id' => '101','name' => 'Конго, демократическая республика','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '102','name' => 'Коста-Рика','currency_code' => 'CRC','currency' => 'Костариканский колон'),
  array('country_id' => '103','name' => 'Кот д`Ивуар','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '104','name' => 'Куба','currency_code' => 'CUP','currency' => 'Кубинское песо'),
  array('country_id' => '105','name' => 'Кувейт','currency_code' => 'KWD','currency' => 'Кувейтский динар'),
  array('country_id' => '11','name' => 'Кыргызстан','currency_code' => 'KGS','currency' => 'Сом'),
  array('country_id' => '106','name' => 'Лаос','currency_code' => 'LAK','currency' => 'Кип'),
  array('country_id' => '12','name' => 'Латвия','currency_code' => 'LVL','currency' => 'Латвийский лат'),
  array('country_id' => '107','name' => 'Лесото','currency_code' => 'LSL','currency' => 'Лоти'),
  array('country_id' => '108','name' => 'Либерия','currency_code' => 'LRD','currency' => 'Либерийский доллар'),
  array('country_id' => '109','name' => 'Ливан','currency_code' => 'LBP','currency' => 'Ливанский фунт'),
  array('country_id' => '110','name' => 'Ливийская Арабская Джамахирия','currency_code' => 'LYD','currency' => 'Ливийский динар'),
  array('country_id' => '13','name' => 'Литва','currency_code' => 'LTL','currency' => 'Литовский лит'),
  array('country_id' => '111','name' => 'Лихтенштейн','currency_code' => 'CHF','currency' => 'Швейцарский франк'),
  array('country_id' => '112','name' => 'Люксембург','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '113','name' => 'Маврикий','currency_code' => 'MUR','currency' => 'Маврикийская рупия'),
  array('country_id' => '114','name' => 'Мавритания','currency_code' => 'MRO','currency' => 'Угия'),
  array('country_id' => '115','name' => 'Мадагаскар','currency_code' => 'MGA','currency' => 'Ариари'),
  array('country_id' => '116','name' => 'Макао','currency_code' => 'MOP','currency' => 'Патака'),
  array('country_id' => '117','name' => 'Македония','currency_code' => 'MKD','currency' => 'Денар'),
  array('country_id' => '118','name' => 'Малави','currency_code' => 'MWK','currency' => 'Квача'),
  array('country_id' => '119','name' => 'Малайзия','currency_code' => 'MYR','currency' => 'Малайзийский ринггит'),
  array('country_id' => '120','name' => 'Мали','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '121','name' => 'Мальдивы','currency_code' => 'MVR','currency' => 'Руфия'),
  array('country_id' => '122','name' => 'Мальта','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '123','name' => 'Марокко','currency_code' => 'MAD','currency' => 'Марокканский дирхам'),
  array('country_id' => '124','name' => 'Мартиника','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '125','name' => 'Маршалловы Острова','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '126','name' => 'Мексика','currency_code' => 'MXN','currency' => 'Мексиканское песо'),
  array('country_id' => '127','name' => 'Микронезия, федеративные штаты','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '128','name' => 'Мозамбик','currency_code' => 'MZN','currency' => 'Мозамбикский метикал'),
  array('country_id' => '15','name' => 'Молдова','currency_code' => 'MDL','currency' => 'Молдавский лей'),
  array('country_id' => '129','name' => 'Монако','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '130','name' => 'Монголия','currency_code' => 'MNT','currency' => 'Тугрик'),
  array('country_id' => '131','name' => 'Монтсеррат','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '132','name' => 'Мьянма','currency_code' => 'MMK','currency' => 'Кьят'),
  array('country_id' => '133','name' => 'Намибия','currency_code' => 'NAD','currency' => 'Доллар Намибии'),
  array('country_id' => '134','name' => 'Науру','currency_code' => 'AUD','currency' => 'Австралийский доллар'),
  array('country_id' => '135','name' => 'Непал','currency_code' => 'NPR','currency' => 'Непальская рупия'),
  array('country_id' => '136','name' => 'Нигер','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '137','name' => 'Нигерия','currency_code' => 'NGN','currency' => 'Найра'),
  array('country_id' => '138','name' => 'Нидерландские Антилы','currency_code' => 'ANG','currency' => 'Нидерландский антильский гульден'),
  array('country_id' => '139','name' => 'Нидерланды','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '140','name' => 'Никарагуа','currency_code' => 'NIO','currency' => 'Золотая кордоба'),
  array('country_id' => '141','name' => 'Ниуэ','currency_code' => 'NZD','currency' => 'Новозеландский доллар'),
  array('country_id' => '142','name' => 'Новая Зеландия','currency_code' => 'NZD','currency' => 'Новозеландский доллар'),
  array('country_id' => '143','name' => 'Новая Каледония','currency_code' => 'XPF','currency' => 'Франк КФП'),
  array('country_id' => '144','name' => 'Норвегия','currency_code' => 'NOK','currency' => 'Норвежская крона'),
  array('country_id' => '145','name' => 'Объединенные Арабские Эмираты','currency_code' => 'AED','currency' => 'Дирхам'),
  array('country_id' => '146','name' => 'Оман','currency_code' => 'OMR','currency' => 'Оманский риал'),
  array('country_id' => '147','name' => 'Остров Мэн','currency_code' => 'GBP','currency' => 'Фунт стерлингов'),
  array('country_id' => '148','name' => 'Остров Норфолк','currency_code' => 'AUD','currency' => 'Австралийский доллар'),
  array('country_id' => '149','name' => 'Острова Кайман','currency_code' => 'KYD','currency' => 'Доллар Островов Кайман'),
  array('country_id' => '150','name' => 'Острова Кука','currency_code' => 'NZD','currency' => 'Новозеландский доллар'),
  array('country_id' => '151','name' => 'Острова Теркс и Кайкос','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '152','name' => 'Пакистан','currency_code' => 'PKR','currency' => 'Пакистанская рупия'),
  array('country_id' => '153','name' => 'Палау','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '154','name' => 'Палестинская автономия','currency_code' => 'ILS','currency' => 'Новый израильский шекель'),
  array('country_id' => '155','name' => 'Панама','currency_code' => 'PAB','currency' => 'Бальбоа'),
  array('country_id' => '156','name' => 'Папуа - Новая Гвинея','currency_code' => 'PGK','currency' => 'Кина'),
  array('country_id' => '157','name' => 'Парагвай','currency_code' => 'PYG','currency' => 'Гуарани'),
  array('country_id' => '158','name' => 'Перу','currency_code' => 'PEN','currency' => 'Новый соль'),
  array('country_id' => '159','name' => 'Питкерн','currency_code' => 'NZD','currency' => 'Новозеландский доллар'),
  array('country_id' => '160','name' => 'Польша','currency_code' => 'PLN','currency' => 'Злотый'),
  array('country_id' => '161','name' => 'Португалия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '162','name' => 'Пуэрто-Рико','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '163','name' => 'Реюньон','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '1','name' => 'Россия','currency_code' => 'RUB','currency' => 'Российский рубль'),
  array('country_id' => '164','name' => 'Руанда','currency_code' => 'RWF','currency' => 'Франк Руанды'),
  array('country_id' => '165','name' => 'Румыния','currency_code' => 'ROL','currency' => 'Лей'),
  array('country_id' => '9','name' => 'США','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '166','name' => 'Сальвадор','currency_code' => 'SVC','currency' => 'Сальвадорский колон'),
  array('country_id' => '167','name' => 'Самоа','currency_code' => 'WST','currency' => 'Тала'),
  array('country_id' => '168','name' => 'Сан-Марино','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '169','name' => 'Сан-Томе и Принсипи','currency_code' => 'STD','currency' => 'Добра'),
  array('country_id' => '170','name' => 'Саудовская Аравия','currency_code' => 'SAR','currency' => 'Саудовский риял'),
  array('country_id' => '171','name' => 'Свазиленд','currency_code' => 'SZL','currency' => 'Лилангени'),
  array('country_id' => '172','name' => 'Святая Елена','currency_code' => 'SHP','currency' => 'Фунт Святой Елены'),
  array('country_id' => '173','name' => 'Северная Корея','currency_code' => 'KPW','currency' => 'Северокорейская вона'),
  array('country_id' => '174','name' => 'Северные Марианские острова','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '175','name' => 'Сейшелы','currency_code' => 'SCR','currency' => 'Сейшельская рупия'),
  array('country_id' => '176','name' => 'Сенегал','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '177','name' => 'Сент-Винсент','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '178','name' => 'Сент-Китс и Невис','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '179','name' => 'Сент-Люсия','currency_code' => 'XCD','currency' => 'Восточно-карибский доллар'),
  array('country_id' => '180','name' => 'Сент-Пьер и Микелон','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '181','name' => 'Сербия','currency_code' => 'RSD','currency' => 'Сербский динар'),
  array('country_id' => '182','name' => 'Сингапур','currency_code' => 'SGD','currency' => 'Сингапурский доллар'),
  array('country_id' => '183','name' => 'Сирийская Арабская Республика','currency_code' => 'SYP','currency' => 'Сирийский фунт'),
  array('country_id' => '184','name' => 'Словакия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '185','name' => 'Словения','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '186','name' => 'Соломоновы Острова','currency_code' => 'SBD','currency' => 'Доллар Соломоновых Островов'),
  array('country_id' => '187','name' => 'Сомали','currency_code' => 'SOS','currency' => 'Сомалийский шиллинг'),
  array('country_id' => '188','name' => 'Судан','currency_code' => 'SDG','currency' => 'Суданский фунт'),
  array('country_id' => '189','name' => 'Суринам','currency_code' => 'SRD','currency' => 'Суринамский доллар'),
  array('country_id' => '190','name' => 'Сьерра-Леоне','currency_code' => 'SLL','currency' => 'Леоне'),
  array('country_id' => '16','name' => 'Таджикистан','currency_code' => 'TJS','currency' => 'Сомони'),
  array('country_id' => '191','name' => 'Таиланд','currency_code' => 'THB','currency' => 'Бат'),
  array('country_id' => '192','name' => 'Тайвань','currency_code' => 'TWD','currency' => 'Новый тайваньский доллар'),
  array('country_id' => '193','name' => 'Танзания','currency_code' => 'TZS','currency' => 'Танзанийский шиллинг'),
  array('country_id' => '194','name' => 'Того','currency_code' => 'XOF','currency' => 'Франк КФА BCEAO'),
  array('country_id' => '195','name' => 'Токелау','currency_code' => 'NZD','currency' => 'Новозеландский доллар'),
  array('country_id' => '196','name' => 'Тонга','currency_code' => 'TOP','currency' => 'Паанга'),
  array('country_id' => '197','name' => 'Тринидад и Тобаго','currency_code' => 'TTD','currency' => 'Доллар Тринидада и Тобаго'),
  array('country_id' => '198','name' => 'Тувалу','currency_code' => 'AUD','currency' => 'Австралийский доллар'),
  array('country_id' => '199','name' => 'Тунис','currency_code' => 'TND','currency' => 'Тунисский динар'),
  array('country_id' => '17','name' => 'Туркмения','currency_code' => 'TMM','currency' => 'Манат'),
  array('country_id' => '200','name' => 'Турция','currency_code' => 'TRL','currency' => 'Турецкая лира'),
  array('country_id' => '201','name' => 'Уганда','currency_code' => 'UGS','currency' => 'Угандийский шиллинг'),
  array('country_id' => '18','name' => 'Узбекистан','currency_code' => 'UZS','currency' => 'Узбекский сум'),
  array('country_id' => '2','name' => 'Украина','currency_code' => 'UAH','currency' => 'Гривна'),
  array('country_id' => '202','name' => 'Уоллис и Футуна','currency_code' => 'XPF','currency' => 'Франк КФП'),
  array('country_id' => '203','name' => 'Уругвай','currency_code' => 'UYP','currency' => 'Уругвайское песо'),
  array('country_id' => '204','name' => 'Фарерские острова','currency_code' => 'DKK','currency' => 'Датская крона'),
  array('country_id' => '205','name' => 'Фиджи','currency_code' => 'FJD','currency' => 'Доллар Фиджи'),
  array('country_id' => '206','name' => 'Филиппины','currency_code' => 'PHP','currency' => 'Филиппинское песо'),
  array('country_id' => '207','name' => 'Финляндия','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '208','name' => 'Фолклендские острова','currency_code' => 'FKP','currency' => 'Фунт Фолклендских островов'),
  array('country_id' => '209','name' => 'Франция','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '210','name' => 'Французская Гвиана','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '211','name' => 'Французская Полинезия','currency_code' => 'XPF','currency' => 'Франк КФП'),
  array('country_id' => '212','name' => 'Хорватия','currency_code' => 'HRK','currency' => 'Хорватская куна'),
  array('country_id' => '213','name' => 'Центрально-Африканская Республика','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '214','name' => 'Чад','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '230','name' => 'Черногория','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '215','name' => 'Чехия','currency_code' => 'CZK','currency' => 'Чешская крона'),
  array('country_id' => '216','name' => 'Чили','currency_code' => 'CLP','currency' => 'Чилийское песо'),
  array('country_id' => '217','name' => 'Швейцария','currency_code' => 'CHF','currency' => 'Швейцарский франк'),
  array('country_id' => '218','name' => 'Швеция','currency_code' => 'SEK','currency' => 'Шведская крона'),
  array('country_id' => '219','name' => 'Шпицберген и Ян Майен','currency_code' => 'NOK','currency' => 'Норвежская крона'),
  array('country_id' => '220','name' => 'Шри-Ланка','currency_code' => 'LKR','currency' => 'Шри-ланкийская рупия'),
  array('country_id' => '221','name' => 'Эквадор','currency_code' => 'USD','currency' => 'Доллар США'),
  array('country_id' => '222','name' => 'Экваториальная Гвинея','currency_code' => 'XAF','currency' => 'Франк КФА BEAC'),
  array('country_id' => '223','name' => 'Эритрея','currency_code' => 'ERN','currency' => 'Накфа'),
  array('country_id' => '14','name' => 'Эстония','currency_code' => 'EUR','currency' => 'Евро'),
  array('country_id' => '224','name' => 'Эфиопия','currency_code' => 'ETB','currency' => 'Эфиопия'),
  array('country_id' => '226','name' => 'Южная Корея','currency_code' => 'KRW','currency' => 'Вона'),
  array('country_id' => '227','name' => 'Южно-Африканская Республика','currency_code' => 'ZAR','currency' => 'Рэнд'),
  array('country_id' => '228','name' => 'Ямайка','currency_code' => 'JMD','currency' => 'Ямайский доллар'),
  array('country_id' => '229','name' => 'Япония','currency_code' => 'JPY','currency' => 'Иена')
);
